### ISSUE TITLE
ArgumentError: Invalid resource type 

### ISSUE THREAD

**Issue by furlongm** [garethr/garethr-kibana#6]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type bundler::install at /etc/puppet/modules/development/kibana/manifests/install.pp:18 on node XX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by furlongm** [comment]
Turns out this was due to the default permissions on the bundler module, closing.

**Comment by rgarner** [comment]
Note to parties that may Google this error in future and apologies to @garethr as this is not directly related to this project - "Invalid resource type bundler::install" can also be caused by not calling your module's directory `bundler`. I'd cloned https://github.com/puppetlabs-operations/puppet-bundler into `puppet-bundler` by mistake.
